name: Debian ARM
on: workflow_dispatch
jobs:
  debian-arm:
    runs-on: ubuntu-latest
    steps:
      - run: |
          sudo apt-get update -q -y
          sudo apt-get -qq install -y qemu qemu-user-static
          docker run --rm --privileged multiarch/qemu-user-static --reset -p yes --credential yes
      - run: |
          docker run --name mycontainer -dit arm64v8/debian /bin/sh
          docker exec -it mycontainer uname -a
