on: push
jobs:
  hello:
    runs-on: macos-12
    steps:
      - uses: actions/checkout@v2
      - uses: actions/cache@v2
        with:
          path: ~/.vagrant.d/boxes
          key: ${{ runner.os }}-vagrant-${{ hashFiles('Vagrantfile') }}
          restore-keys: ${{ runner.os }}-vagrant-
      - run: vagrant --version
      - run: vagrant up
      - run: vagrant ssh -c "echo 'hello world!'"
  hello-workflow-ln:
    uses: ./w.yml@main
  hello-workflow:
    uses: ./.github/workflows/workflow.yml@main
